---
- name: Create directory for persistant volume if it does not exist
  ansible.builtin.file:
    path: "/auto-gen-docs-ansible"
    state: directory
    mode: '0740'

- name: Insert system.md file
  ansible.builtin.template:
    src: system.j2
    dest: "/auto-gen-docs-ansible/system.md"
    owner: "root"
    group: "root"
    mode: '0740'

- name: Fetch the system.md to ansible-host docs folder 
  fetch: 
    src: "/auto-gen-docs-ansible/system.md"
    dest: "docs/{{ inventory_hostname }}/system.md"
    flat: yes