---



- name: Insert hardware.md file
  ansible.builtin.template:
    src: hardware.md
    dest: "/auto-gen-docs-ansible/hardware.md"
    owner: "root"
    group: "root"
    mode: '0740'

- name: Fetch the system.md to ansible-host docs folder 
  fetch: 
    src: "/auto-gen-docs-ansible/hardware.md"
    dest: "docs/{{ inventory_hostname }}/hardware.md"
    flat: yes

- name: Write down facts
  template:
    src: "facts_tpl.j2"
    dest: "/auto-gen-docs-ansible/facts.log"