---



- name: Insert hardware.md file
  ansible.builtin.template:
    src: hardware.md
    dest: "/auto-gen-docs-ansible/hardware.md"
    owner: "root"
    group: "root"
    mode: '0740'

- name: Fetch the hardware.md to ansible-host docs folder 
  fetch: 
    src: "/auto-gen-docs-ansible/hardware.md"
    dest: "docs/{{ inventory_hostname }}/hardware.md"
    flat: yes
